package:
  name: micromummie
  version: 1.0.0

source:
  fn: micromummie_without_tgs.tgz
  url: https://github.com/BIMSBbioinfo/bioconda-recipes/raw/micromummie/recipes/micromummie/micromummie_without_tgs.tgz
  md5: 0966493df60e1770f7ecfff5e093f641

build:
  skip: True  # [not linux]
  number: 2

requirements:
  build:
    - openmpi
    - perl-bioperl
    - perl-file-chdir
    - gsl ==1.16
    - ucsc-twobittofa
    - bedtools ==2.24
    - perl
  run:
    - openmpi
    - perl-bioperl
    - perl-file-chdir
    - gsl ==1.16
    - ucsc-twobittofa
    - bedtools ==2.24
    - perl

test:
  commands:
    - microMUMMIE.pl 2>&1 | grep 'microMUMMIE.pl' > /dev/null
    - baum-welch 2>&1 | grep 'baum-welch' > /dev/null

about:
  home: https://ohlerlab.mdc-berlin.de/software/microMUMMIE_99/
  license: GPL (>= 2)
  summary: 'This is a pipeline to predict micro-RNA
  binding sites using PAR-CLIP data'

extra:
  recipe-maintainers:
    - dyusuf
