package:
  name: bioconductor-biocparallel
  version: 1.9.3
source:
  fn: BiocParallel_1.9.3.tar.gz
  url: https://bioarchive.galaxyproject.org/BiocParallel_1.9.3.tar.gz
  md5: 09746acc9a8ba0d0256955ba456e1320
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r
    - r-futile.logger
    - r-snow
  run:
    - r
    - r-futile.logger
    - r-snow
test:
  commands:
    - '$R -e "library(''BiocParallel'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/BiocParallel.html
  license: 'GPL-2 | GPL-3'
  summary: 'This package provides modified versions and novel implementation of functions
    for parallel evaluation, tailored to use with Bioconductor objects.'
