package:
  name: bioconductor-org.hs.eg.db
  version: 3.4.0
source:
  fn: org.Hs.eg.db_3.4.0.tar.gz
  url: http://bioconductor.org/packages/release/data/annotation/src/contrib/org.Hs.eg.db_3.4.0.tar.gz
  md5: b7e7b5e49d6aa833c655a56d338f8812
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-annotationdbi >=1.35.4'
    - r
  run:
    - 'bioconductor-annotationdbi >=1.35.4'
    - r
test:
  commands:
    - '$R -e "library(''org.Hs.eg.db'')"'
about:
  home: http://bioconductor.org/packages/release/data/annotation/html/org.Hs.eg.db.html
  license: Artistic-2.0
  summary: 'Genome wide annotation for Human, primarily based on mapping using Entrez
    Gene identifiers.'
