package:
  name: bioconductor-s4vectors
  version: "0.12.1"

source:
  fn: S4Vectors_0.12.1.tar.gz
  url: https://bioconductor.org/packages/release/bioc/src/contrib/S4Vectors_0.12.1.tar.gz
  md5: eb60f1687fb123e2d745d91afa128d6c

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

#Suggests: 	IRanges, GenomicRanges, Matrix, ShortRead, graph, data.table, RUnit

#I specify the versions of respective dependencies while buiding the package,
#whereas in the comments, I document
#the version ranges specified in the origianl R description file.
requirements:
  build:
    - bioconductor-biocgenerics >=0.15.10
    - r #>=3.3.0
  run:
    - bioconductor-biocgenerics >=0.15.10
    - r #>=3.3.0

test:
  commands:
    - $R -e "library('S4Vectors')"

about:
  home: http://bioconductor.org/packages/release/bioc/html/S4Vectors.html
  license: Artistic-2.0
  summary: 'The S4Vectors package defines the Vector and List virtual classes and
    a set of generic functions that extend the semantic of ordinary vectors and lists
    in R. Package developers can easily implement vector-like or list-like objects
    as concrete subclasses of Vector or List. In addition, a few low-level concrete
    subclasses of general interest (e.g. DataFrame, Rle, and Hits) are implemented
    in the S4Vectors package itself (many more are implemented in the IRanges package
    and in other Bioconductor infrastructure packages).'
